import fastifyMultipart from "@fastify/multipart";
import type { FastifyInstance } from "fastify";
import {
  BACK_OFFICE_ROLES,
  currentUser,
  requireAuth,
  requireRole
} from "../../auth/middleware.js";
import { prisma } from "../../db/prisma.js";
import { badRequest } from "../../lib/http-error.js";
import { presentLocation } from "../../lib/present.js";
import { loadLocation } from "../../lib/scope.js";
import { createLocationBody, idParams, updateLocationBody } from "../../schemas/index.js";

// 2 MB, independent of app.ts's global 128 KB JSON bodyLimit -- @fastify/multipart
// streams the body itself rather than going through the JSON parser that limit
// guards. SVG is deliberately excluded from the mime whitelist below: a restaurant
// logo is a raster photo or a simple mark in practice, and dropping vector art
// removes an entire category of "did we get the serving headers exactly right"
// XSS reasoning from the launch.
const LOGO_MAX_BYTES = 2 * 1024 * 1024;
const ALLOWED_LOGO_MIME_TYPES = new Set(["image/png", "image/jpeg", "image/webp"]);

export default async function adminLocationRoutes(app: FastifyInstance): Promise<void> {
  app.addHook("preHandler", requireAuth);
  app.addHook("preHandler", requireRole(...BACK_OFFICE_ROLES));

  await app.register(fastifyMultipart, { limits: { fileSize: LOGO_MAX_BYTES } });

  app.get("/locations", async (request) => {
    const user = currentUser(request);
    const locations = await prisma.location.findMany({
      where: user.role === "SUPER_ADMIN" ? {} : { id: user.locationId ?? "" },
      orderBy: { name: "asc" }
    });
    return { locations: locations.map(presentLocation) };
  });

  // Creating a tenant is not a per-location action, so it stays with the only role
  // that is not itself scoped to a location.
  app.post("/locations", { preHandler: requireRole("SUPER_ADMIN") }, async (request, reply) => {
    const body = createLocationBody.parse(request.body);
    const location = await prisma.location.create({ data: body });
    return reply.status(201).send({ location: presentLocation(location) });
  });

  app.get("/locations/:id", async (request) => {
    const { id } = idParams.parse(request.params);
    return { location: presentLocation(await loadLocation(request, id)) };
  });

  app.patch("/locations/:id", async (request) => {
    const { id } = idParams.parse(request.params);
    const body = updateLocationBody.parse(request.body);
    await loadLocation(request, id);
    const location = await prisma.location.update({ where: { id }, data: body });
    return { location: presentLocation(location) };
  });

  // A new upload creates a new LocationAsset row and repoints logoAssetId rather
  // than overwriting bytes in place -- that's what makes the immutable cache
  // header on GET .../logo safe (see docs/multi-tenant-branding-plan.md). The old
  // row is simply left orphaned; cleaning those up isn't worth it yet.
  app.post("/locations/:id/logo", async (request, reply) => {
    const { id } = idParams.parse(request.params);
    const location = await loadLocation(request, id);

    const file = await request.file();
    if (!file) throw badRequest("No file uploaded");
    if (!ALLOWED_LOGO_MIME_TYPES.has(file.mimetype)) {
      throw badRequest("Unsupported image type. Use PNG, JPEG or WEBP.");
    }

    // Throws FST_REQ_FILE_TOO_LARGE (413) if the stream exceeds LOGO_MAX_BYTES --
    // @fastify/multipart's default throwFileSizeLimit behaviour, left as-is so it
    // reaches the generic error handler.
    const buffer = await file.toBuffer();

    const asset = await prisma.locationAsset.create({
      data: {
        locationId: location.id,
        mimeType: file.mimetype,
        // A plain Uint8Array<ArrayBuffer> copy -- Buffer's own type is backed by
        // ArrayBufferLike (which admits SharedArrayBuffer), narrower than what
        // Prisma's generated Bytes type expects.
        data: Uint8Array.from(buffer),
        size: buffer.length
      }
    });

    const updated = await prisma.location.update({
      where: { id: location.id },
      data: { logoAssetId: asset.id }
    });

    return reply.status(201).send({ location: presentLocation(updated) });
  });
}
